"use client";

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useMemo,
  ReactNode,
} from "react";
import { translations, type TranslationKeys } from "@/src/translations";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationKeys;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language | undefined>(undefined);
  const [isClient, setIsClient] = useState(false);
  const [forceUpdate, setForceUpdate] = useState(0); // Add force update trigger

  // Ensure we're on client side
  useEffect(() => {
    setIsClient(true);
  }, []);

  // Load language from localStorage on mount
  useEffect(() => {
    if (!isClient) return;
    
    const savedLanguage = localStorage.getItem("adminLanguage") as Language;
    
    if (savedLanguage && (savedLanguage === "vi" || savedLanguage === "en")) {
      setLanguage(savedLanguage);
    } else {
      setLanguage("en"); // fallback default to English
      // Also set in localStorage immediately
      localStorage.setItem("adminLanguage", "en");
    }
  }, [isClient]);

  // Save language to localStorage when changed
  useEffect(() => {
    if (language && isClient) {
      localStorage.setItem("adminLanguage", language);
    }
  }, [language, isClient]);

  const handleSetLanguage = (lang: Language) => {
    // Force localStorage update immediately and synchronously
    if (isClient) {
      localStorage.setItem("adminLanguage", lang);
    }
    
    // Update state even if same language to force refresh
    setLanguage(lang);
    
    // Force re-render
    setForceUpdate(prev => prev + 1);
  };

  // Use useMemo to ensure translation object updates when language changes
  const t = useMemo(() => {
    // Always return a valid translation object, prioritize English
    const currentLang = language || "en"; // Default to English
    let translation = translations[currentLang];
    
    // Fallback to English if current language not available
    if (!translation || typeof translation !== 'object') {
      translation = translations.en;
    }
    
    // Final safety check - ensure we have a valid translation object
    if (!translation || typeof translation !== 'object') {
      return createFallbackTranslation();
    }
    
    return translation as TranslationKeys;
  }, [language, forceUpdate, isClient]);

  // Helper function to create comprehensive fallback translation
  function createFallbackTranslation(): TranslationKeys {
    return {
      dashboard: "Dashboard",
      users: "Users", 
      moderators: "Moderators",
      reports: "Reports",
      matches: "Matches",
      subscriptions: "Subscriptions",
      addAccount: "Add Account",
      dashboardOverview: "Dashboard Overview",
      totalUsers: "Total Users",
      activeUsersToday: "Active Users Today",
      totalMatches: "Total Matches",
      totalMessages: "Total Messages",
      admin: "ADMIN",
      moderator: "MODERATOR",
      user: "USER", 
      role: "Role",
      username: "Username",
      firstName: "First Name",
      lastName: "Last Name",
      phoneNumber: "Phone Number",
      adding: "Adding...",
      totalUsersPlatform: "Total users on the platform",
      activeUsersTodayDesc: "Users active today",
      totalMatchesPlatform: "Total matches on the platform",
      totalMessagesSent: "Total messages sent",
      fromLastMonth: "from last month",
      view: "View",
      userGrowth: "User Growth",
      newUsersPerDay: "New users per day (last 30 days)",
      matchingSuccessRate: "Matching Success Rate",
      totalSwipesVsMatches: "Total swipes vs matches (last 30 days)",
      recentUsers: "Recent Users",
      latestUserRegistrations: "Latest user registrations",
      status: "Status",
      joinDate: "Join Date",
      location: "Location",
      actions: "Actions",
      noUsersFound: "No users found.",
      newUsers: "New Users",
      totalSwipes: "Total Swipes",
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      close: "Close",
      details: "Details",
      active: "Active",
      inactive: "Inactive", 
      suspended: "Suspended",
      userManagement: "User Management",
      addUser: "Add User",
      editUser: "Edit User",
      deleteUser: "Delete User",
      suspendUser: "Suspend User",
      restoreUser: "Restore User",
      userDetails: "User Details",
      userList: "User List",
      activeUsers: "Active Users",
      suspendedUsers: "Suspended Users",
      moderatorManagement: "Moderator Management",
      addModerator: "Add Moderator",
      editModerator: "Edit Moderator",
      deleteModerator: "Delete Moderator",
      moderatorDetails: "Moderator Details",
      moderatorList: "Moderator List",
      totalModerators: "Total Moderators",
      activeModerators: "Active Moderators",
      reportsHandled: "Reports Handled",
      lastActive: "Last Active",
      reportManagement: "Report Management",
      reportDetails: "Report Details",
      reportList: "Report List",
      pendingReports: "Pending Reports",
      resolvedReports: "Resolved Reports",
      reportType: "Report Type",
      reportReason: "Report Reason",
      reportedBy: "Reported By",
      reportedUser: "Reported User",
      reportDate: "Report Date",
      resolveReport: "Resolve Report",
      rejectReport: "Reject Report",
      matchManagement: "Match Management",
      matchDetails: "Match Details",
      matchList: "Match List",
      successfulMatches: "Successful Matches",
      subscriptionManagement: "Subscription Management",
      subscriptionDetails: "Subscription Details",
      subscriptionList: "Subscription List",
      totalSubscriptions: "Total Subscriptions",
      activeSubscriptions: "Active Subscriptions",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      permissions: "Permissions",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      bio: "Bio",
      interests: "Interests",
      generalSettings: "General Settings",
      appearanceSettings: "Appearance",
      notificationSettings: "Notifications",
      securitySettings: "Security",
      changePassword: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      theme: "Theme",
      language: "Language",
      primaryColor: "Primary Color",
      fontSize: "Font Size",
      loginSuccess: "Login successful",
      loginError: "Please enter email and password",
      userCreated: "User created successfully",
      userUpdated: "User updated successfully",
      userDeleted: "User deleted successfully",
      userSuspended: "User suspended successfully",
      userRestored: "User restored successfully",
      moderatorCreated: "Moderator created successfully",
      moderatorUpdated: "Moderator updated successfully",
      moderatorDeleted: "Moderator deleted successfully",
      reportResolved: "Report resolved successfully",
      reportRejected: "Report rejected successfully",
      passwordChanged: "Password changed successfully",
      settingsUpdated: "Settings updated successfully",
      requiredField: "This field is required",
      invalidEmail: "Invalid email address",
      passwordMismatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 8 characters",
      networkError: "Network error occurred",
      unknownError: "An unknown error occurred",
      confirmDeleteUser: "Are you sure you want to delete this user?",
      confirmSuspendUser: "Are you sure you want to suspend this user?",
      confirmRestoreUser: "Are you sure you want to restore this user?",
      confirmDeleteModerator: "Are you sure you want to delete this moderator?",
      confirmResolveReport: "Are you sure you want to resolve this report?",
      confirmRejectReport: "Are you sure you want to reject this report?",
      today: "Today",
      yesterday: "Yesterday",
      thisWeek: "This week",
      thisMonth: "This month",
      minutesAgo: "minutes ago",
      hoursAgo: "hours ago",
      daysAgo: "days ago",
      filterBy: "Filter by",
      sortBy: "Sort by",
      searchPlaceholder: "Search...",
      noResults: "No results found",
      loading: "Loading...",
      refresh: "Refresh",
      page: "Page",
      of: "of",
      itemsPerPage: "items per page",
      previous: "Previous",
      next: "Next",
      first: "First",
      last: "Last",
      success: "Success",
      error: "Error",
      warning: "Warning",
      info: "Information",
      successfully: "successfully",
      failed: "failed",
      loadingText: "Loading...",
      saving: "Saving...",
      deleting: "Deleting...",
      processing: "Processing...",
      completed: "Completed",
      cancelled: "Cancelled",
      suspendedText: "suspended",
      restored: "restored",
      noModeratorsFound: "No moderators found matching your criteria",
      noReportsFound: "No reports found matching your criteria",
      searchModerators: "Search moderators...",
      searchUsers: "Search users...",
      searchReports: "Search reports...",
      featureComingSoon: "Feature coming soon",
      featureUnavailable: "Feature temporarily unavailable due to backend limitations",
      unknownUser: "Unknown User",
      unknownEmail: "No email",
      backendUnavailable: "Backend service unavailable",
      invalidDate: "Invalid date",
      unknown: "Unknown",
      filterByStatus: "Filter by status",
      allStatuses: "All statuses",
      allReports: "All reports",
      pending: "Pending",
      resolved: "Resolved",
      dismissed: "Dismissed",
      export: "Export",
      noDataAvailable: "No data available",
      reportId: "Report ID",
      type: "Type",
      date: "Date",
      reportDetailsDescription: "Detailed information about the selected report.",
      viewDetails: "View details",
      markAsResolved: "Mark as resolved",
      dismissReport: "Dismiss report",
      authenticationError: "Authentication error occurred",
      failedToLoadUsers: "Failed to load users",
      failedToLoadUserDetails: "Failed to load user details",
      failedToSuspendUser: "Failed to suspend user",
      failedToRestoreUser: "Failed to restore user",
      suspendedByAdmin: "Suspended by admin",
      restoredByAdmin: "Restored by admin",
      userSuspendedTitle: "User has been suspended",
      userRestoredTitle: "User has been restored",
      userRestoredMessage: "User has been restored and can now access the platform.",
      errorTitle: "Error",
      expandSidebar: "Expand sidebar",
      collapseSidebar: "Collapse sidebar",
      resetSettings: "Reset",
      saveChanges: "Save Changes",
      systemName: "System Name",
      supportEmail: "Support Email",
      defaultTimezone: "Default Timezone",
      defaultLanguage: "Default Language",
      maintenanceMessage: "Maintenance Message",
      manageSytemSettings: "Manage system settings and preferences",
      systemNameDescription: "This name will be displayed throughout the admin interface",
      supportEmailDescription: "This email will be used for system notifications and user support requests",
      selectTimezone: "Select timezone",
      utcTime: "UTC (Coordinated Universal Time)",
      estTime: "EST (Eastern Standard Time)",
      cstTime: "CST (Central Standard Time)",
      mstTime: "MST (Mountain Standard Time)",
      pstTime: "PST (Pacific Standard Time)",
      timezoneDescription: "System-wide default timezone for displaying dates and times",
      selectLanguage: "Select language",
      english: "English",
      languageDescription: "System-wide default language",
      maintenanceMessagePlaceholder: "Enter message to display during maintenance mode",
      maintenanceMessageDefault: "We are performing scheduled maintenance. Please check back later.",
      maintenanceMessageDescription: "This message will be shown to users when maintenance mode is enabled",
      savingText: "Saving...",
      settingsUpdatedTitle: "Settings Updated",
      settingsUpdatedDescription: "Your general settings have been updated successfully.",
      noData: "No data",
      reportInformation: "Report Information",
      reporter: "Reporter",
      description: "Description",
      suspendUserTitle: "Suspend User",
      suspendUserDescription: "Are you sure you want to suspend this user? They will not be able to access the platform until restored.",
      suspensionReason: "Suspension Reason",
      inappropriateContent: "Inappropriate Content",
      harassment: "Harassment",
      fakeProfile: "Fake Profile",
      underageUser: "Underage User",
      other: "Other",
      suspensionDuration: "Suspension Duration",
      oneDay: "1 Day",
      threeDays: "3 Days",
      sevenDays: "7 Days",
      thirtyDays: "30 Days",
      permanent: "Permanent",
      resolveReportTitle: "Resolve Report",
      resolveReportDescription: "Mark this report as resolved. This will close the report and notify the reporter.",
      resolutionNotes: "Resolution Notes (Optional)",
      enterResolutionDetails: "Enter resolution details",
      notifyReporter: "Notify reporter about resolution",
      dismissReportTitle: "Dismiss Report",
      dismissReportDescription: "Dismiss this report as invalid or requiring no action.",
      reasonForDismissal: "Reason for dismissal",
      noViolationFound: "No violation found",
      insufficientEvidence: "Insufficient evidence",
      duplicateReport: "Duplicate report",
      misunderstanding: "Misunderstanding",
      additionalNotes: "Additional Notes (Optional)",
      enterAdditionalDetails: "Enter additional details",
      selectAReason: "Select a reason",
      selectDuration: "Select duration",
      assignedTo: "Assigned to",
      fourteenDays: "14 Days",
      ninetyDays: "90 Days",
      addAdminModeratorAccount: "Add Admin / Moderator Account",
      addAdminAccount: "Add Admin Account",
      addModeratorAccount: "Add Moderator Account",
      enterEmail: "Enter email",
      enterUsername: "Enter username",
      enterFirstName: "Enter first name",
      enterLastName: "Enter last name",
      enterPhoneNumber: "Enter phone number",
      moderatorRole: "Moderator",
      temporaryPassword: "Temporary Password",
      defaultPassword: "Default: Amoura123@",
      showPasswordText: "Show password",
      searchUsersByNameEmailUsername: "Search users by name, email, or username...",
      allStatusesFilter: "All Statuses",
      userColumn: "User",
      contact: "Contact",
      activity: "Activity",
      created: "Created",
      userDetailsModal: "User Details",
      detailedInformationSelectedUser: "Detailed information about the selected user.",
      userId: "User ID",
      hasProfile: "Has Profile",
      yes: "Yes",
      no: "No",
      photoCount: "Photo Count",
      lastLogin: "Last Login",
      createdAt: "Created At",
      totalMatchesUser: "Total Matches",
      totalMessagesUser: "Total Messages",
      restoreUserAction: "Restore User",
      viewDetailsAction: "View Details",
      totalUsersCount: "Total users",
      currentPage: "current page",
      previousPage: "Previous",
      nextPage: "Next",
      matchManagementNotAvailable: "Match management feature is not available yet",
      featureComingSoonText: "Feature coming soon",
      matchManagementFeatureNotAvailable: "Match management feature is not available yet",
      myProfile: "My Profile",
      myProfileTitle: "My Profile",
      updatedAt: "Updated At",
      confirmNewPassword: "Confirm New Password",
      changePasswordTitle: "Change Password",
      currentPasswordField: "Current Password",
      newPasswordField: "New Password",
      changePasswordButton: "Change Password",
      general: "General",
      security: "Security",
      notifications: "Notifications",
      appearance: "Appearance",
      settingsTitle: "Settings",
      generalSettingsTab: "General Settings",
      manageSystemSettings: "Manage your system-wide settings and preferences",
      systemNameField: "System Name",
      amouraAdminDashboardTitle: "Amoura Admin Dashboard",
      thisNameDisplayed: "This name will be displayed throughout the admin interface",
      supportEmailField: "Support Email",
      supportEmailDefault: "support@amoura.space",
      emailUsedForSystemNotifications: "This email will be used for system notifications and user support requests",
      defaultTimezoneField: "Default Timezone",
      utcCoordinatedUniversalTime: "UTC (Coordinated Universal Time)",
      systemWideDefaultTimezone: "System-wide default timezone for displaying dates and times",
      defaultLanguageField: "Default Language",
      englishLanguage: "English",
      systemWideDefaultLanguage: "System-wide default language",
      maintenanceMessageField: "Maintenance Message",
      currentlyPerformingMaintenance: "We're currently performing scheduled maintenance. Please check back soon.",
      messageDisplayedMaintenanceMode: "This message will be displayed to users when maintenance mode is enabled",
      reset: "Reset",
      saveChangesButton: "Save Changes",
      notificationSettingsTitle: "Notification Settings",
      notificationSettingsUpdated: "Your notification preferences have been updated successfully.",
      notificationSettingsDescription: "Configure which notifications you receive and how they are delivered",
      appearanceSettingsTitle: "Appearance Settings",
      appearanceSettingsUpdated: "Your appearance settings have been updated successfully.",
      themeLabel: "Theme",
      lightTheme: "Light",
      darkTheme: "Dark",
      systemTheme: "System",
      fontSizeLabel: "Font Size",
      mediumFontSize: "Medium",
      comfortableDensity: "Comfortable",
      enabledAnimations: "Enabled",
      updatePasswordSecure: "Update your password to keep your account secure",
      showPassword: "Show password",
      passwordRequirements: "Password must be at least 8 characters with uppercase, lowercase, numbers, and special characters.",
      securitySettingsUpdated: "Your security settings have been updated successfully.",
      manageSecuritySettings: "Manage security settings and authentication preferences",
      twoFactorAuthentication: "Two-Factor Authentication",
      twoFactorAuthDescription: "Require administrators to use two-factor authentication when logging in",
      sessionTimeout: "Session Timeout",
      sessionTimeoutDescription: "Automatically log out administrators after a period of inactivity",
      selectTimeoutPeriod: "Select timeout period",
      fifteenMinutes: "15 minutes",
      thirtyMinutes: "30 minutes",
      oneHour: "1 hour",
      twoHours: "2 hours",
      fourHours: "4 hours",
      ipAddressRestriction: "IP Address Restriction",
      ipRestrictionDescription: "Restrict admin access to specific IP addresses",
      allowedIpAddresses: "Allowed IP Addresses",
      enterIpAddresses: "Enter IP addresses, one per line",
      ipAddressesDescription: "Only these IP addresses will be allowed to access the admin dashboard",
      passwordPolicy: "Password Policy",
      selectPasswordPolicy: "Select password policy",
      basicPolicy: "Basic (8+ characters)",
      mediumPolicy: "Medium (8+ chars, letters & numbers)",
      strongPolicy: "Strong (8+ chars, upper/lowercase, numbers, symbols)",
      customPolicy: "Custom Policy",
      passwordPolicyDescription: "Set the password complexity requirements for admin accounts",
      auditLogging: "Audit Logging",
      auditLoggingDescription: "Log all administrator actions for security and compliance",
      configureNotifications: "Configure which notifications you receive and how they are delivered",
      emailNotifications: "Email Notifications",
      newUserRegistrations: "New User Registrations",
      receiveEmailNewUsers: "Receive an email when new users register",
      userReports: "User Reports",
      receiveEmailUserReports: "Receive an email when a user submits a report",
      premiumSubscriptions: "Premium Subscriptions",
      receiveEmailPremiumSubscriptions: "Receive an email when a user purchases a premium subscription",
      systemAlerts: "System Alerts",
      receiveEmailSystemAlerts: "Receive an email for important system alerts and warnings",
      dashboardNotifications: "Dashboard Notifications",
      showNotificationsNewUsers: "Show notifications for new user registrations",
      showNotificationsUserReports: "Show notifications for new user reports",
      showNotificationsPremiumSubscriptions: "Show notifications for new premium subscriptions",
      showNotificationsSystemAlerts: "Show notifications for system alerts and warnings",
      notificationDigest: "Notification Digest",
      dailyDigest: "Daily Digest",
      receiveDailySummary: "Receive a daily summary of all notifications",
      weeklyDigest: "Weekly Digest",
      receiveWeeklySummary: "Receive a weekly summary of all notifications",
      resetToDefaults: "Reset to Defaults",
      customizeLookAndFeel: "Customize the look and feel of your admin dashboard",
      light: "Light",
      dark: "Dark",
      system: "System",
      medium: "Medium",
      adjustFontSize: "Adjust the font size throughout the admin interface",
      interfaceDensity: "Interface Density",
      comfortable: "Comfortable",
      adjustSpacingDensity: "Adjust the spacing and density of UI elements",
      animations: "Animations",
      enabled: "Enabled",
      controlAnimations: "Control the level of animations throughout the interface",
      selectFontSize: "Select font size",
      selectInterfaceDensity: "Select interface density",
      selectAnimationPreference: "Select animation preference",
      small: "Small",
      large: "Large",
      compact: "Compact",
      spacious: "Spacious",
      reduced: "Reduced",
      disabled: "Disabled",
      currentPasswordRequired: "Current password is required",
      newPasswordRequired: "New password is required",
      newPasswordMinLength: "New password must be at least 8 characters",
      newPasswordComplexity: "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
      confirmPasswordRequired: "Please confirm your new password",
      passwordsDoNotMatch: "Passwords do not match",
      newPasswordMustBeDifferent: "New password must be different from current password",
      passwordUpdatedSuccessfully: "Your password has been updated successfully",
      passwordChangedSuccessfully: "Password Changed Successfully",
      passwordUpdatedLoginAgain: "Your password has been updated. Please log in again with your new password.",
      passwordChangeFailed: "Password Change Failed",
      unableToChangePassword: "Unable to change password. Please check your current password and try again.",
      unexpectedErrorOccurred: "An unexpected error occurred. Please try again later.",
      changePasswordDescription: "Update your password to keep your account secure",
      advancedThemeCustomization: "Advanced Theme Customization",
      accountsTitle: "Accounts",
      accountManagement: "Account Management",
      manageAdminModeratorAccounts: "Manage Admin and Moderator Accounts",
      addNewAccount: "Add New Account",
      searchAccounts: "Search accounts...",
      name: "Name",
      statusColumn: "Status",
      actionsColumn: "Actions",
      userGrowthLabel: "User Growth",
      newUsersPerDayLabel: "New users per day (last 30 days)",
      matchingSuccessRateLabel: "Matching Success Rate",
      totalSwipesVsMatchesLabel: "Total swipes vs matches (last 30 days)",
      recentUsersLabel: "Recent Users",
      latestUserRegistrationsLabel: "Latest user registrations",
      temporaryPasswordLabel: "Temporary Password",
      temporaryPasswordDescription: "A temporary password will be generated and sent to the user",
      online: "Online",
      offline: "Offline",
      away: "Away",
      busy: "Busy",
      viewProfile: "View Profile",
      editProfile: "Edit Profile",
      deleteAccount: "Delete Account",
      suspendAccount: "Suspend Account",
      activateAccount: "Activate Account",
      resetPassword: "Reset Password",
      sendMessage: "Send Message",
      quickActions: "Quick Actions",
      recentActivity: "Recent Activity",
      systemStatus: "System Status",
      accountCreatedSuccessfully: "Account created successfully",
      accountCreationInitiated: "Account creation initiated. Check email for further steps.",
      accountUpdatedSuccessfully: "Account updated successfully",
      accountDeletedSuccessfully: "Account deleted successfully",
      accountSuspendedSuccessfully: "Account suspended successfully",
      accountActivatedSuccessfully: "Account activated successfully",
      passwordResetSuccessfully: "Password reset successfully",
      errorMessage: "Error",
      temporaryPasswordPlaceholder: "Temporary password",
      emailRequired: "Email is required",
      usernameRequired: "Username is required",
      firstNameRequired: "First name is required",
      lastNameRequired: "Last name is required",
      phoneNumberRequired: "Phone number is required",
      roleRequired: "Role is required",
      selectRole: "Select Role",
      adminRole: "Admin",
      selectStatus: "Select Status",
      allRoles: "All Roles",
      header: {
        searchPlaceholder: "Search users, reports, or moderators...",
        notifications: "Notifications",
        profile: "Profile",
        settings: "Settings",
        logout: "Log out",
        viewAllNotifications: "View all notifications",
        light: "Light",
        dark: "Dark",
        system: "System",
        adminUser: "Admin User",
        adminEmail: "admin@amoura.space",
      },
      footer: {
        title: "Amoura Admin Dashboard",
        description: "Manage your dating platform with powerful tools and insights",
        madeWith: "Made with",
        forAdministrators: "for administrators",
        quickLinks: "Quick Links",
        support: "Support",
        helpCenter: "Help Center",
        privacy: "Privacy Policy",
        terms: "Terms of Service",
        legal: "Legal",
        copyright: "© 2024 Amoura. All rights reserved.",
        contact: "Contact Us"
      },
      login: {
        title: "Admin Login",
        subtitle: "Sign in to your admin dashboard",
        email: "Email",
        password: "Password",
        emailPlaceholder: "admin@amoura.space",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        rememberMe: "Remember me",
        welcomeBack: "Welcome back!",
        invalidCredentials: "Invalid email or password",
        loginSuccess: "Login successful!"
      }
    } as TranslationKeys;
  }
  const value: LanguageContextType = {
    language: language || "en", // Default to English
    setLanguage: handleSetLanguage,
    t: t || translations.en as TranslationKeys, // Ensure t is never undefined
  };

  if (!isClient) {
    // Show loading or default content on server side
    return (
      <LanguageContext.Provider value={value}>
        {children}
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider value={value} key={`${language}-${forceUpdate}`}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
