
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    REGISTER_INITIATE: "/auth/register/initiate",
    REGISTER_RESEND_OTP: "/auth/register/resend-otp",
    REGISTER_VERIFY_OTP: "/auth/register/verify-otp",
    REGISTER_COMPLETE: "/auth/register/complete",
    PASSWORD_RESET_REQUEST: "/auth/password/reset/request",
    PASSWORD_RESET_VERIFY_OTP: "/auth/password/reset/verify-otp",
    PASSWORD_RESET: "/auth/password/reset",
    PASSWORD_RESET_RESEND_OTP: "/auth/password/reset/resend-otp",
    EMAIL_AVAILABLE: "/auth/email-available",
    LOGIN_OTP_REQUEST: "/auth/login/otp/request",
    PROFILE: "/user",
    CHANGE_PASSWORD: "/user/change-password",
    CHANGE_EMAIL_REQUEST: "/user/change-email/request",
    CHANGE_EMAIL_CONFIRM: "/user/change-email/confirm",
  },
  USER: {
    GET: "/user",
    PATCH: "/user",
    ONLINE: (id: string) => `/users/${id}/online`,
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    USER_BY_ID: (id: string) => `/admin/users/${id}`,
    USER_SEARCH: "/admin/users/search",
    UPDATE_USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    MODERATORS: "/admin/moderators",
    REPORTS: "/admin/reports",
    STATS: "/admin/stats",
    SUBSCRIPTIONS: "/admin/subscriptions",
  },
  MODERATION: {
    USERS: "/moderation/users",
    USER_BY_ID: (id: string) => `/moderation/users/${id}`,
    USER_SEARCH: "/moderation/users/search",
    UPDATE_USER_STATUS: (id: string) => `/moderation/users/${id}/status`,
  },
  PROFILE: {
    ME: "/profiles/me",
    BY_ID: (id: string) => `/profiles/${id}`,
    OPTIONS: "/profiles/options",
    PHOTOS: "/profiles/photos",
    PHOTOS_HIGHLIGHTS: "/profiles/photos/highlights",
    PHOTOS_COVER: "/profiles/photos/cover",
    PHOTOS_AVATAR: "/profiles/photos/avatar",
    PHOTOS_BY_USER: (id: string) => `/profiles/photos/${id}`,
    PHOTOS_HIGHLIGHTS_BY_USER: (id: string) => `/profiles/photos/${id}/highlights`,
    PHOTOS_COVER_BY_USER: (id: string) => `/profiles/photos/${id}/cover`,
    PHOTOS_AVATAR_BY_USER: (id: string) => `/profiles/photos/${id}/avatar`,
  },
  MATCHING: {
    SWIPE: "/matching/swipe",
    RECOMMENDATIONS: "/matching/recommendations",
    RECEIVED: "/matching/received",
  },
  CHAT: {
    ROOMS: "/chat/rooms",
    ROOM_BY_ID: (id: string) => `/chat/rooms/${id}`,
    MESSAGES: (id: string) => `/chat/rooms/${id}/messages`,
    MESSAGES_READ: (id: string) => `/chat/rooms/${id}/messages/read`,
    MESSAGES_UNREAD_COUNT: (id: string) => `/chat/rooms/${id}/messages/unread-count`,
    UPLOAD_IMAGE: "/chat/upload-image",
    MESSAGE_RECALL: (id: string) => `/chat/messages/${id}/recall`,
    MESSAGE_DELETE_FOR_ME: (id: string) => `/chat/messages/${id}/delete-for-me`,
    DELETE_MESSAGE: (id: string) => `/chat/messages/${id}/delete`,
    DELETE_IMAGE: "/chat/delete-image",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD: "/notifications/unread",
    UNREAD_COUNT: "/notifications/unread/count",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
} as const;

export const STORAGE_KEYS = {
  AUTH_TOKEN: "auth_token",
  REFRESH_TOKEN: "refresh_token",
  USER_DATA: "user_data",
  SIDEBAR_COLLAPSED: "sidebar_collapsed",
  THEME: "theme",
  PRIMARY_COLOR: "primary_color",
  FONT_SIZE: "font_size",
  ADMIN_AVATAR: "admin_avatar",
} as const;

export const QUERY_KEYS = {
  USERS: ["users"],
  USER: (id: string) => ["users", id],
  PROFILES: ["profiles"],
  PROFILE: (id: string) => ["profiles", id],
  CHAT_ROOMS: ["chat", "rooms"],
  MESSAGES: (roomId: string) => ["chat", "messages", roomId],
  NOTIFICATIONS: ["notifications"],
  MATCHING: ["matching"],
  ADMIN_STATS: ["admin", "stats"],
} as const;
