name: amoura
description: "A new Flutter project."

publish_to: 'none'

# The version number of the app. The first part is the version name and the second part is the build number.
version: 1.0.0+1

environment:
  sdk: ^3.7.2 # Dart SDK version

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter # Flutter SDK

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

# The development dependencies are packages that are only needed during development.
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3 # for generating app icons
  flutter_animate: ^4.5.2 # for animations
  flutter_lints: ^5.0.0 # for linting
  google_fonts: ^6.2.1 # for custom fonts
  font_awesome_flutter: ^10.8.0 # for Font Awesome icons
  shimmer: ^3.0.0 # for shimmer effect
  photo_view: ^0.15.0 # for image viewing


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # uses-material-design is a flag that enables Material Design
  uses-material-design: true

  # assets are files that are bundled with the application
  assets:
    - assets/images/dark_amoura.png
    - assets/icons/light_amoura.png
    - assets/images/welcome_find_your_match.png
    - assets/images/welcome_safe_secure.png
    - assets/images/welcome_start_chatting.png

# assets are files that are bundled with the application
flutter_icons:
  android: true # generate icons for Android
  ios: true # generate icons for iOS
  image_path: "assets/images/dark_amoura.png" # path to the icon image
  adaptive_icon_background: "#ffffff" # background color of the adaptive icon
  adaptive_icon_foreground: "assets/images/dark_amoura.png" # foreground image of the adaptive icon
