name: amoura
description: "A new Flutter project."

publish_to: 'none'

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_animate: ^4.5.2
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # uses-material-design is a flag that enables Material Design
  uses-material-design: true

  # assets are files that are bundled with the application
  assets:
    - assets/images/dark_amoura.png
    - assets/icons/light_amoura.png
    - assets/images/welcome_find_your_match.png
    - assets/images/welcome_safe_secure.png
    - assets/images/welcome_start_chatting.png

# assets are files that are bundled with the application
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dark_amoura.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/dark_amoura.png"
