INSERT INTO body_types (name, created_at, updated_at)
VALUES
    ('Slim', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Average', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Athletic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Muscular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Curvy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Plus-size', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Prefer not to say', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
