# Test Application Configuration
spring.application.name=Amoura Dating App - Test

# Test Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/amoura_test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:test_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:test_password}

# JPA Configuration for Tests
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# Logging Configuration for Tests
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.amoura=DEBUG 