spring.datasource.url=jdbc:postgresql://localhost:5432/amoura
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

logging.level.com.amoura=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

file.storage.local.upload-dir=${FILE_UPLOAD_DIR:/opt/uploads}
file.storage.local.base-url=${FILE_BASE_URL:http://150.95.109.13:8080/api/files